name: CD Pipeline

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"


      - name: Set SHA
        run: echo "GIT_SHA=${{ github.sha }}" >> $GITHUB_ENV



      - name: Build dependencies
        run: |
          mkdir -p build
          pip install -r requirements.txt -t build/
          cd build
          zip -r ../dependencies.zip .

      - name: Upload dependencies
        run: |
          aws s3 cp dependencies.zip s3://bucket/libs/dependencies-${GIT_SHA}.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1

      - name: Upload Glue jobs to S3
        run: |
          aws s3 cp frontend/src/jobs/etl_offers.py s3://$S3_BUCKET/scripts/etl_offers-${GIT_SHA}.py
          aws s3 cp frontend/src/jobs/etl_sales.py s3://$S3_BUCKET/scripts/etl_sales-${GIT_SHA}.py
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
