name: CI/CD Pipeline
on:
  workflow_dispatch:

jobs:

  infra-provisioning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Terraform Repo
        uses: actions/checkout@v4
        with:
          repository: https://github.com/mohamedamine050/projet_smart-grid
          token: ${{ secrets.GH_TOKEN }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}


      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

      - name: Terraform Output
        run: terraform output -json > tf_output.json